### ISSUE TITLE
/packages/yogiben:bootstrap/bootstrap.import.less wasn't found

### ISSUE THREAD

**Issue by dasniko** [yogiben/meteor-bootstrap#1]
I tried to include your package as described, but
- I had to add manually the `less` package, although it's a dependency, it didn't work, all less files were ignored
- after adding the less-package, I get the following error during server startup:
  `client/bootstrap.less:2:1: Less compiler error: '/packages/yogiben:bootstrap/bootstrap.import.less' wasn't found`

I'm using Meteor 0.9.4
Thanks for help!

**Comment by yogiben** [comment]
Unfortunately, Meteor has changed a lot recently.

I updated the readme today. Sorry for wasting your time.
